[package]
org = "ballerina_tests"
name = "sftp_connection_tests"
version = "2.17.2"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "ftp"
version = "2.17.2"
repository = "local"

[[dependency]]
org = "ballerina_tests"
name = "ftp_test_commons"
version = "2.17.2"
repository = "local"
