[package]
org = "ballerina_tests"
name = "ftp_listener_advanced_tests"
version = "2.20.1"
distribution = "2201.14.0-20260527-050400-74f7e6bf"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "ftp"
version = "2.20.1"
repository = "local"

[[dependency]]
org = "ballerina_tests"
name = "ftp_test_commons"
version = "2.20.1"
repository = "local"
